CREATE TABLE "{database}"."{table_prefix}charCharacterSheet" (
    "allianceID"        BIGINT(20) UNSIGNED          DEFAULT 0,
    "allianceName"      CHAR(50)                     DEFAULT '',
    "ancestry"          CHAR(24)            NOT NULL,
    "ancestryID"        BIGINT(20) UNSIGNED NOT NULL,
    "balance"           DECIMAL(17,2)       NOT NULL,
    "bloodLine"         CHAR(24)            NOT NULL,
    "bloodLineID"       BIGINT(20) UNSIGNED NOT NULL,
    "characterID"       BIGINT(20) UNSIGNED NOT NULL,
    "cloneJumpDate"     DATETIME            NOT NULL DEFAULT '1970-01-01 00:00:01',
    "corporationID"     BIGINT(20) UNSIGNED NOT NULL,
    "corporationName"   CHAR(50)            NOT NULL,
    "DoB"               DATETIME            NOT NULL,
    "factionID"         BIGINT(20) UNSIGNED          DEFAULT 0,
    "factionName"       CHAR(50)                     DEFAULT '',
    "freeRespecs"       INT(4) UNSIGNED     NOT NULL DEFAULT 0,
    "freeSkillPoints"   BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
    "gender"            CHAR(6)             NOT NULL,
    "homeStationID"     BIGINT(20) UNSIGNED NOT NULL,
    "jumpActivation"    DATETIME            NOT NULL,
    "jumpFatigue"       DATETIME            NOT NULL,
    "jumpLastUpdate"    DATETIME            NOT NULL,
    "lastRespecDate"    DATETIME            NOT NULL DEFAULT '1970-01-01 00:00:01',
    "lastTimedRespec"   DATETIME            NOT NULL DEFAULT '1970-01-01 00:00:01',
    "name"              CHAR(50)            NOT NULL,
    "race"              CHAR(8)             NOT NULL,
    "remoteStationDate" DATETIME            NOT NULL,
    PRIMARY KEY ("characterID")
)
ENGINE = { engine}
COLLATE utf8_unicode_ci;
